// This is a placeholder for your AWS configuration.
// Typically, this file is auto-generated by the Amplify CLI, 
// but you can maintain it manually if you prefer.

const awsmobile = {
    // Basic config
    "aws_project_region": "us-east-1", // e.g., us-east-1
    
    // Cognito Auth Config
    "aws_cognito_region": "us-east-1", // e.g., us-east-1
    "aws_user_pools_id": "us-east-1_xxxxxxxxx", // Your User Pool ID
    "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxxxxxxxxxxxxx", // Your Web Client ID
    
    // Auth requirements
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};

export default awsmobile;
